sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 120.24.43.189
    port: 3306
    database: sky_take_out
    username: root
    password: JRd4XzGWCzeQvqMX


#spring:
#  datasource:
#    url: jdbc:mysql://120.24.43.189:3306/ssm_demo?serverTimezone=UTC
#    username: root
#    password: JRd4XzGWCzeQvqMX
#    driver-class-name: com.mysql.cj.jdbc.Driver