sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 120.24.43.189
    port: 3306
    database: sky_take_out
    username: root
    password: JRd4XzGWCzeQvqMX


#spring:
#  datasource:
#    url: jdbc:mysql://120.24.43.189:3306/ssm_demo?serverTimezone=UTC
#    username: root
#    password: JRd4XzGWCzeQvqMX
#    driver-class-name: com.mysql.cj.jdbc.Driver

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast

  redis:
    host: 120.24.43.189
    port: 6379
    password: wq34gevFr
    database: 0

  wechat:
    appid: wx3032a8d7e8e72a04
    secret: fefe214b4a3a16fe99b065a81fd24bd4
